export default function Head() {
  return (
    <>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <meta
        name="viewport"
        content="width=device-width, height=device-height, initial-scale=1, shrink-to-fit=no, viewport-fit=cover"
      />
    </>
  )
}
